import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";
import toml from "toml";
import type { DevLogConfig } from "./types.js";
import {
  getClaudeProjectsDir,
  getDevlogDir,
  getConfigPath,
} from "../utils/paths.js";

const DEFAULT_CONFIG = `# DevLog Configuration
# Auto-generated by devlog

[paths]
# Claude Code projects directory
claude_dir = "{{claudeDir}}"

# DevLog data directory
devlog_dir = "{{devlogDir}}"

[display]
# Maximum number of sessions to show in list
max_sessions = 50

# Truncate message preview to this length
preview_length = 80
`;

export function isInitialized(): boolean {
  return existsSync(getConfigPath());
}

export function initConfig(): DevLogConfig {
  const devlogDir = getDevlogDir();
  const claudeDir = getClaudeProjectsDir();
  const configPath = getConfigPath();

  mkdirSync(devlogDir, { recursive: true });
  mkdirSync(join(devlogDir, "daily"), { recursive: true });
  mkdirSync(join(devlogDir, "reports"), { recursive: true });
  mkdirSync(join(devlogDir, "db"), { recursive: true });

  const configContent = DEFAULT_CONFIG.replace(
    "{{claudeDir}}",
    claudeDir
  ).replace("{{devlogDir}}", devlogDir);

  writeFileSync(configPath, configContent, "utf-8");

  return { claudeDir, devlogDir, version: "0.1.0" };
}

/**
 * Ensure DevLog is initialized. Returns config + whether this was the first run.
 */
export function ensureInit(): { config: DevLogConfig; isFirstRun: boolean } {
  if (!isInitialized()) {
    return { config: initConfig(), isFirstRun: true };
  }
  return { config: loadConfig(), isFirstRun: false };
}

export function loadConfig(): DevLogConfig {
  const configPath = getConfigPath();

  if (!existsSync(configPath)) {
    return {
      claudeDir: getClaudeProjectsDir(),
      devlogDir: getDevlogDir(),
      version: "0.1.0",
    };
  }

  try {
    const raw = readFileSync(configPath, "utf-8");
    const parsed = toml.parse(raw);

    return {
      claudeDir: parsed.paths?.claude_dir || getClaudeProjectsDir(),
      devlogDir: parsed.paths?.devlog_dir || getDevlogDir(),
      version: "0.1.0",
    };
  } catch {
    return {
      claudeDir: getClaudeProjectsDir(),
      devlogDir: getDevlogDir(),
      version: "0.1.0",
    };
  }
}
